spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tw?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

# rabbitmq
  application:
    name: springboot-rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: xxf
    password: 123456
    cache:
      channel:
        size: 8

# redis
  redis:
#    host: localhost
    password: 123456
#    port: 6379

# Server settings (ServerProperties)
server:
  port: 8084
  servlet:
    context-path: /

log:
  level: INFO
  path: D:/logs/springboot_demo

cors:
  allowedOrigins: 'http://192.168.1.116:8088'