spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tw?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  #上传文件配置
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 200MB

  # rabbitmq
#  application:
#    name: springboot-rabbitmq
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    cache:
#      channel:
#        size: 8

  #Dubbo 配置
#  dubbo:
#    application:
#      id: springboot_demo
#      name: springboot_demo
#    registry:
#      address: zookeeper://127.0.0.1:2181
#    protocol:
#      name: dubbo
#      port: 20800

  # redis
#  redis:
    #    host: localhost
#    password: 123456
#    port: 6379

# Server settings (ServerProperties)
server:
  port: 8084
  servlet:
    context-path: /

log:
  level: INFO
  path: C:/logs/springboot_demo

cors:
  allowedOrigins: 'http://192.168.1.116:8088'