spring:
  profiles.active: dev
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    cache-period: 0

mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mapper/*Mapper.xml